namespace WorkforceAPI.Models.DTOs;

/// <summary>
/// Data Transfer Object for dashboard summary information
/// </summary>
/// <remarks>
/// This DTO aggregates various statistics and information for the dashboard view.
/// It provides a comprehensive overview of the workforce management system including:
/// - Employee statistics (total, active)
/// - Project statistics (total, active)
/// - Task statistics (total, completed)
/// - Leave request statistics
/// - Department headcount breakdown
/// - Project progress information
/// - Leave statistics by type
/// - Recent activity feed
/// 
/// This DTO is typically generated by the DashboardService which aggregates data
/// from multiple sources (PostgreSQL for employees/projects/tasks, MongoDB for leave requests).
/// </remarks>
public class DashboardSummaryDto
{
    /// <summary>
    /// Total number of employees in the system
    /// </summary>
    public int TotalEmployees { get; set; }
    
    /// <summary>
    /// Number of active employees (IsActive = true)
    /// </summary>
    public int ActiveEmployees { get; set; }
    
    /// <summary>
    /// Total number of projects in the system
    /// </summary>
    public int TotalProjects { get; set; }
    
    /// <summary>
    /// Number of active projects (Status = "Active")
    /// </summary>
    public int ActiveProjects { get; set; }
    
    /// <summary>
    /// Total number of tasks in the system
    /// </summary>
    public int TotalTasks { get; set; }
    
    /// <summary>
    /// Number of completed tasks (Status = "Done")
    /// </summary>
    public int CompletedTasks { get; set; }
    
    /// <summary>
    /// Number of pending leave requests (Status = "Pending")
    /// </summary>
    public int PendingLeaveRequests { get; set; }
    
    /// <summary>
    /// List of department headcounts (employee count per department)
    /// </summary>
    /// <remarks>
    /// Provides a breakdown of how many employees are in each department.
    /// Used for department distribution charts and statistics.
    /// </remarks>
    public List<DepartmentHeadcountDto> DepartmentHeadcount { get; set; } = new();
    
    /// <summary>
    /// List of project progress information
    /// </summary>
    /// <remarks>
    /// Provides progress information for each project including:
    /// - Total tasks and completed tasks
    /// - Progress percentage
    /// - Project status
    /// Used for project progress charts and statistics.
    /// </remarks>
    public List<ProjectProgressDto> ProjectProgress { get; set; } = new();
    
    /// <summary>
    /// Leave request statistics
    /// </summary>
    /// <remarks>
    /// Provides aggregated leave request statistics including:
    /// - Total requests, approved, pending, rejected counts
    /// - Breakdown by leave type (Sick, Casual, Annual, Unpaid)
    /// Used for leave statistics charts and displays.
    /// </remarks>
    public LeaveStatisticsDto LeaveStatistics { get; set; } = new();
    
    /// <summary>
    /// List of recent activity items
    /// </summary>
    /// <remarks>
    /// Contains recent audit log entries or system events.
    /// Used for activity feed displays on the dashboard.
    /// The structure is flexible (object) to accommodate different activity types.
    /// </remarks>
    public List<object> RecentActivity { get; set; } = new();
}

/// <summary>
/// Data Transfer Object for department headcount information
/// </summary>
/// <remarks>
/// Used in DashboardSummaryDto to provide employee count per department.
/// </remarks>
public class DepartmentHeadcountDto
{
    /// <summary>
    /// Department unique identifier (as string for JSON serialization)
    /// </summary>
    public string DepartmentId { get; set; } = string.Empty;
    
    /// <summary>
    /// Department name
    /// </summary>
    public string DepartmentName { get; set; } = string.Empty;
    
    /// <summary>
    /// Number of employees in this department
    /// </summary>
    public int Count { get; set; }
}

/// <summary>
/// Data Transfer Object for project progress information
/// </summary>
/// <remarks>
/// Used in DashboardSummaryDto to provide progress information for each project.
/// </remarks>
public class ProjectProgressDto
{
    /// <summary>
    /// Project unique identifier (as string for JSON serialization)
    /// </summary>
    public string ProjectId { get; set; } = string.Empty;
    
    /// <summary>
    /// Project name
    /// </summary>
    public string ProjectName { get; set; } = string.Empty;
    
    /// <summary>
    /// Project status (e.g., "Active", "Completed", "OnHold")
    /// </summary>
    public string Status { get; set; } = string.Empty;
    
    /// <summary>
    /// Total number of tasks in the project
    /// </summary>
    public int TotalTasks { get; set; }
    
    /// <summary>
    /// Number of completed tasks in the project
    /// </summary>
    public int CompletedTasks { get; set; }
    
    /// <summary>
    /// Progress percentage (0-100)
    /// </summary>
    /// <remarks>
    /// Calculated as: (CompletedTasks / TotalTasks) * 100
    /// Used for progress bars and charts.
    /// </remarks>
    public int ProgressPercentage { get; set; }
}

/// <summary>
/// Data Transfer Object for leave request statistics
/// </summary>
/// <remarks>
/// Used in DashboardSummaryDto to provide aggregated leave request statistics.
/// </remarks>
public class LeaveStatisticsDto
{
    /// <summary>
    /// Total number of leave requests
    /// </summary>
    public int TotalRequests { get; set; }
    
    /// <summary>
    /// Number of approved leave requests
    /// </summary>
    public int Approved { get; set; }
    
    /// <summary>
    /// Number of pending leave requests
    /// </summary>
    public int Pending { get; set; }
    
    /// <summary>
    /// Number of rejected leave requests
    /// </summary>
    public int Rejected { get; set; }
    
    /// <summary>
    /// Breakdown of leave requests by type
    /// </summary>
    /// <remarks>
    /// Dictionary key: Leave type (e.g., "Sick", "Casual", "Annual", "Unpaid")
    /// Dictionary value: Count of requests for that type
    /// Example: { "Sick": 10, "Annual": 25, "Casual": 5 }
    /// </remarks>
    public Dictionary<string, int> ByType { get; set; } = new();
}
